name: chatgpt_client
description: A sample ChatGPT client built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dart_openai: ^1.8.0
  flutter:
    sdk: flutter
  markdown_widget: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true